version: '3'

dotenv: [.env]
interval: 300ms

tasks:
  format:
    run: when_changed
    cmds:
      - go fmt ./...

  lint:
    run: when_changed
    requires:
      vars: [APP_ENV]
    cmds:
      - go vet ./...
      - golangci-lint run ./...

  typecheck:
    run: when_changed
    cmds:
      - nilaway ./...

  audit:
    run: when_changed
    deps: [not_implemented]

  run:
    cmds: 
      - task: test

  dev:
    sources: ["**/*.go"]
    watch: true
    method: none
    cmds: 
      - task: devtest

  test:
    cmds:
      - gotest -count=1 ./...

  devtest:
    sources: ["**/*.go"]
    watch: true
    method: none
    cmds:
      - gotest -count=1 -failfast ./...

  coverage:
    deps: [format, lint, test]
    cmds:
      - gotest -count=1 ./... -coverprofile .coverage.out

  bench:
    cmds:
      - gobench ./...

  build:
    deps: [format, lint, test]