version: '3'

dotenv: [.env]
interval: 300ms

tasks:
  format:
    run: when_changed
    cmds:
      - go fmt -v ./...

  lint:
    run: when_changed
    requires:
      vars: [APP_ENV]
    cmds:
      - go vet -v ./...

  typecheck:
    run: when_changed
    cmds:
      - nilaway ./...


  audit:
    run: when_changed
    deps: [not_implemented]

  run:
    cmds: 
      - task: test

  dev:
    sources: ["**/*.go"]
    watch: true
    cmds: 
      - task: devtest

  test:
    cmds:
      - gotest -v ./...

  devtest:
    sources: ["**/*.go"]
    watch: true
    cmds:
      - gotest -v ./...

  coverage:
    deps: [format, lint, test]
    cmds:
      - gotest -v ./... -coverprofile .coverage.out     

  build:
    deps: [format, lint, test, coverage]